export const NEW_AUTH_ERROR_MESSAGE_KEY = "NEW_AUTH";
export const USER_LOGIN_ERROR_MESSAGE_KEY = "USER_LOGIN";
export const USER_LOGOUT_ERROR_MESSAGE_KEY = "USER_LOGOUT";
export const USER_REGISTER_ERROR_MESSAGE_KEY = "USER_REGISTER";
