export const ADD_OUTLET_ERROR_MESSAGE_KEY = "ADD_OUTLET";
export const DAY_SCHEDULE_ERROR_MESSAGE_KEY = "DAY_SCHEDULE";
export const OUTLET_ITEM_ERROR_MESSAGE_KEY = "OUTLET_ITEM";
export const UPDATE_OUTLET_ERROR_MESSAGE_KEY = "UPDATE_OUTLET";
